### ISSUE TITLE
Tried to compile

### ISSUE THREAD

**Issue by jocmer** [dude719/UEFI-Bootkit#2]
Hi dude,

I tried to compile your UEFI Driver.. But I get a weird error which i am not able to solve...

The errors are in "SimpleFileSystem" which is included from "edk2\EdkCompatibilityPkg\Foundation\Efi\Protocol\SimpleFileSystem\SimpleFileSystem.c":
- cannot open source file "EfiSpec.h"

Thanks for your help!

**Comment by jocmer** [comment]
my SimpleFileSystem.c:

[code]
#include "EfiSpec.h"
#include EFI_PROTOCOL_DEFINITION (SimpleFileSystem)

EFI_GUID  gEfiSimpleFileSystemProtocolGuid = EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID;

EFI_GUID_STRING(&gEfiSimpleFileSystemProtocolGuid, "Filesystem Protocol", "EFI 1.0 Simple FileSystem Protocol");
[/code]

**Comment by dude719** [comment]
Don't even bother with this.
